name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ELM_HOME: ~/.elm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - run: npm ci
        env:
          NO_ELM_TOOLING_INSTALL: 1

      - name: Cache ELM_HOME
        uses: actions/cache@v5
        with:
          path: ${{ env.ELM_HOME }}
          key: elm-${{ hashFiles('elm.json', 'elm-tooling.json', 'review/elm.json') }}
          restore-keys: elm-

      - run: npx elm-tooling install
      - run: npx elm make --docs docs.json
      - run: npx elm-format --validate src/ example/src
      - run: npx elm-review

  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - run: npm ci
        env:
          NO_ELM_TOOLING_INSTALL: 1

      - name: Cache ELM_HOME
        uses: actions/cache@v5
        with:
          path: ${{ env.ELM_HOME }}
          key: elm-${{ hashFiles('elm.json', 'elm-tooling.json', 'review/elm.json') }}
          restore-keys: elm-

      - run: npx elm-tooling install

      - name: Install example deps
        run: npm ci
        working-directory: example

      - name: Build Elm
        run: npm run build
        working-directory: example
